name: Claude Code Plan
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited, labeled, unlabeled]
jobs:
  claude-response:
    if: contains(github.event.issue.labels.*.name, 'claude')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          direct_prompt: |
            Issueとコメントの内容を確認し、コードベースをもとに実装は行わず分析して、実装計画を考えてください。
            その後、考えた実装計画から以下の点をユーザーにフィードバックしてください。
            - 変更内容の3行程度のサマリー
            - 主に変更されるファイルと変更内容
            - 不足している情報をユーザーに質問
            英語で考えて、最終的なアウトプットだけ日本語で出力してください。
